name: cryoarc
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  # Core
  - python=3.10
  - biopython
  - numpy
  - git
  - pandas
  - scipy
  - tqdm
  - typing-extensions
  - pip

  # CUDA / PyTorch
  - pytorch::pytorch=2.5
  - pytorch::pytorch-cuda=12.4
  - cuda
  - pytorch-lightning

  # OpenFold
  - gcc=12.4
  - setuptools=59.5.0
  - openmm
  - pdbfixer
  - PyYAML
  - requests
  - wandb
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - mkl
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2

  
  - pip:
      # OpenFold 
      - deepspeed==0.14.5
      - dm-tree==0.1.6
      - git+https://github.com/NVIDIA/dllogger.git

      # Cryodrgn
      - cryodrgn

      #- flash-attn 
